---
title: "Coursework Template"
subtitle: 'MSc in Statistics 2025/26, Imperial College London'
author: "Joaquín Mosquera Brito"
format:
  html:
    toc: true
    highlight: tango
    self-contained: true
    df-print: paged
  pdf: default
format-links: false
bibliography: "ref.bib" 
---

<style type="text/css">
h1{
  font-size: 24pt;
}
h2{
  font-size: 18pt;
}
body{
  font-size: 12pt;
}
</style>

```{r setup, include = FALSE, tidy=TRUE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
include_solutions <- TRUE
```
```{r setup2, include=FALSE, tidy=TRUE}
require(rmarkdown)
require(knitr)
require(kableExtra)
# Put any library imports and other preamble here.
```

```{r}
#| warning: false
library(palmerpenguins)
penguins <- palmerpenguins::penguins
```

# Penguin bill depth vs length

```{r}
#| echo: false
#| fig-cap: "Penguin bill depth vs length"
plot(x = penguins$bill_length_mm,
y = penguins$bill_depth_mm, 
main = "Penguin bill dimensions",
sub = "Data source: Palmer Penguins")

```
# Penguin mean and median body mass

```{r}
#| results: hold
mean(penguins$body_mass_g, na.rm = TRUE)
median(penguins$body_mass_g, na.rm = TRUE)
```
# How many penguins are there in each island?


```{r}
#| label: n_penguins_in_islands
#| tbl-cap: "Number of penguins in each island"
island_counts <- table(penguins$island)
knitr::kable(island_counts, col.names = c("Island", "Number of penguins"))
```


# Is the average weight of penguins the same across all three islands?

```{r echo=FALSE}
#| fig-cap: "Penguin body mass by island"
plot(x = penguins$island, 
     y = penguins$body_mass_g, 
     ylab = "Body mass (g)", 
     xlab = "Island",
     col(c(6, 3, 4)))
abline(h = mean(penguins$body_mass_g,na.rm = TRUE), col = 2, lwd = 2)
```



# References
